### ISSUE TITLE
Critrate value is displayed wrong

### ISSUE THREAD

**Issue by haifrosch** [karaeren/loa-details#10]
The critrate value is being displayed wrong. Seems like the values are in reverse (100% critrate = displayed as 0%)
![image](https://user-images.githubusercontent.com/4474225/169656659-fb437145-1707-4cf3-8dc8-7818d8644239.png)

**Comment by haifrosch** [comment]
Seems to be a bug with LostArkLogger that might have been introduced in v0.0.5.0 and v0.0.5.1.
Critrate values are also displayed wrong on LostArkLogger

**Comment by karaeren** [comment]
Fixed a4789dfac8efe4ffcff9903b3a7c2eb750d5da36
