### ISSUE TITLE
Dps meter doesn't register packets after update

### ISSUE THREAD

**Issue by momocorpo** [karaeren/loa-details#16]
After Vykas update the damage isn't registered anymore, anyone having this issue?

**Comment by FlexxDW** [comment]
I can confirm I am having the same issue, not working since the latest patch.

**Comment by karaeren** [comment]
This is already known and a recurring thing after every major update and has nothing to do with loa-details. It's related to the logger itself.

**Comment by FlexxDW** [comment]
So when will the DPS meter work again?
