### ISSUE TITLE
Window drag

### ISSUE THREAD

**Issue by Zejjx** [karaeren/loa-details#17]
Window is not draggable when mousedown on the "Total DMG" and "Total DPS" (red) labels in the caption. The timer (green) label works as expected.

![image](https://user-images.githubusercontent.com/70071380/177254393-3c1d71c2-be24-4dd7-a8c8-a96dac217f77.png)

**Comment by karaeren** [comment]
This is due to that place having a right-click menu for enabling/disabling features to display there. Not a bug or anything.
