### ISSUE TITLE
Avg Damage below 1k is not rounded

### ISSUE THREAD

**Issue by leanleon93** [karaeren/loa-details#20]
It looks like in the skill view the AvgDmg below 1k is not rounded so the text in the cell overflows.
![avgdmg-bug](https://user-images.githubusercontent.com/31262614/178221939-2d1430bb-080c-4163-bbbf-422100e9c610.png)

**Comment by karaeren** [comment]
fixed e85f3e529aa30fe1a7d55ee7deb060366bac2f32
