### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by zhatiana** [karaeren/loa-details#21]
I need to know which file to download. Then how to operate. I don't know how to use it. It's best to have a head to tail video tutorial or an uploaded video tutorial address. thank you

**Comment by KelvinJs** [comment]
**The connection to the packet capture service was lost error**

There could be multiple reasons for this.

Net Framework: If you have Windows installed freshly, you might not have required libraries such as .NET Framework 4.8 or higher. Installing this could work. https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-offline-installer

Firewall: There is a popup screen when you install LOA Details for the first time where it asks you for firewall access. That is not optional! If you didn't click Allow when that popped up, you have to manually add "LostArkLogger.exe" that is located in the LOA Details folder to the firewall.

Antivirus: Some antiviruses might block LostArkLogger.exe. You can try to add it to ignored list/whitelist or whatever it is called. Avast especially doesn't seem to like it.
