### ISSUE TITLE
After update, was an autoupdater installed and selected to start with windows?

### ISSUE THREAD

**Issue by Boomaay** [karaeren/loa-details#25]
![image](https://user-images.githubusercontent.com/110171968/181497524-1244f1eb-ef70-48e0-8830-1ddaaedf8a78.png)

?

**Comment by karaeren** [comment]
No, that's not related to this app. You can view the origin of that startup by going to task manager > startup > right click and properties. It should tell you what executable that points to.

**Comment by Boomaay** [comment]
> No, that's not related to this app. You can view the origin of that startup by going to task manager > startup > right click and properties. It should tell you what executable that points to.
> 
> Edit: That's probably Discord. I have the same thing and it has Discord logo with it, just fyi.

thank you! i bet you are correct, let me delete this in an hour or so just so i dont make people feel suspiscious or anything
