### ISSUE TITLE
Lost connection to Lost Ark Packet Capture

### ISSUE THREAD

**Issue by ChungHoward** [karaeren/loa-details#28]
Started occurring when version 0.6.0 was released. Can't use an older version due to auto-update.

![image](https://user-images.githubusercontent.com/6575846/183063739-f1e5e720-dadd-40ba-87c3-92881f2b4fe7.png)

What causes this?

**Comment by Poopieee** [comment]
Also having this issue, I tried reinstalling it, didn't work ):

**Comment by zhatiana** [comment]
The computer will not have this problem at home. This problem will occur if Internet cafes are used

**Comment by ChungHoward** [comment]
> The computer will not have this problem at home. This problem will occur if Internet cafes are used

I used this at home. There are no internet cafes in my country.

**Comment by karaeren** [comment]
Check out the Discord server for known problems/troubleshooting.
