### ISSUE TITLE
No data generation

### ISSUE THREAD

**Issue by zhatiana** [karaeren/loa-details#29]
Before version 0.5.5, it can be used normally. After that, the content on the picture will appear, and no data will be generated.
![微信图片_20220806141138](https://user-images.githubusercontent.com/104927390/183237010-be8b35a3-abe9-4b8a-b7ca-f05cf50241e2.png)

**Comment by zhatiana** [comment]
@karaeren   Today, the new 0.6.1 also has no data. How to solve it

**Comment by zhatiana** [comment]
The latest version v0.6.4 has no output data at present. What's wrong with me? No DPS data has been generated   https://github.com/karaeren  @karaeren    Can you help me with this?

**Comment by zhatiana** [comment]
I really want to use it, but I still have no data with the new version 0.6.5. Can you reply to me? Where is the problem? How to solve it

**Comment by karaeren** [comment]
There are many solutions to general problems such as this on the Discord server. Just check out there. This place isn't really for troubleshooting. Also, this is a problem with the logger, not LOA Details.
